### PR TITLE
Config patch 2

### PR DESCRIPTION
**Pull request by planetexpress69**
Hello Ben, the current way to poke the api key out of the config file does not work for me. Please review yet again. And many thanks for fixing bugs and for keeping everything up-to-date.

### CODE REVIEW

**Comment by bdvholmes** [comment]
Hi @planetexpress69 thanks for the PR! I'll review asap.

**Comment by halfdan** [comment]
@bdvholmes That moment when you aren't sure whether the "s" in asap stands for soon or slow.. :D Could we get a pretty merge and release please señor? :)

**Comment by bdvholmes** [comment]
@halfdan as sorry as possible

**Comment by bdvholmes** [comment]
Thank you so much for your submission @planetexpress69

**Comment by bdvholmes** [comment]
Released in [v0.2.0](https://github.com/bdvholmes/ember-cli-mapbox/releases/tag/v0.2.0)

**Comment by planetexpress69** [comment]
De nada, compañero.

**Pull request merged**
